### ISSUE TITLE
Crash on unload when running through QGIS python interpreter

### ISSUE THREAD

**Issue by nyalldawson** [pcraster/pcraster#361]
Whenever the pcraster python library is installed, QGIS crashes on exit due to the pcraster library trying to deregister the loaded GDAL drivers, when the QGIS application shutdown has already handled this externally.

See eg https://github.com/qgis/QGIS/issues/49242

I'm wondering if this could be handled using some logic like this:

1. When pcraster library is loaded, test whether GDAL drivers have already been initialised within the environment (e.g. by checking whether an "always available" driver like the shapefile driver is available). If they've already been loaded, remember this in a global static bool somewhere
2. During library unload, only deregister GDAL drivers IF pcraster was responsible for loading them (ie. by checking that global static bool)

**Comment by OliverSchmitz** [comment]
Hello,
thanks for reporting and your suggestions. It's already supposed to work like that, but I think the problem is located somewhere else in our code. Working on it...

**Comment by OliverSchmitz** [comment]
We fixed a segfault and released a new version, that should solve this issue

**Comment by rodreras** [comment]
Hey, guys. In version QGIS 3.22.11 and 3.22.14 I still face the same problem when existing QGIS. My PCRaster version is 0.2.0
 

Here is all information that I provided for the issue in the QGIS Repository 

https://github.com/qgis/QGIS/issues/51488

Is there anything I can do to solve it?

**Comment by OliverSchmitz** [comment]
thanks for reporting, we'll check it again

**Comment by rodreras** [comment]
Just reinstalled PCRaster and upgraded QGIS to 3.28 Firenze, now it closes properly!

**Comment by OliverSchmitz** [comment]
Thanks for the update! I still keep #371 open as I'd like to exactly figure out what is happening at module exit...
